# Generated by Django 5.0.7 on 2024-08-25 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.TextField()),
                ('date', models.DateField()),
                ('document_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('electricity_condition', models.CharField(max_length=255)),
                ('gas_condition', models.CharField(max_length=255)),
                ('structural_integrity', models.CharField(max_length=255)),
                ('mould_damp_condition', models.CharField(max_length=255)),
                ('asbestos_condition', models.CharField(max_length=255)),
                ('security_risk', models.CharField(max_length=255)),
                ('report', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
