# Generated by Django 5.0.7 on 2024-08-19 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('details', models.TextField()),
                ('completion_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('report_photos', models.FileField(blank=True, null=True, upload_to='maintenance/')),
                ('report', models.TextField()),
                ('performed_by', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('due_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('upcoming_photo', models.FileField(blank=True, null=True, upload_to='maintenance/upcoming/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repair_score', models.FloatField()),
                ('repair_history', models.TextField()),
                ('completion_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('completion_report', models.TextField()),
                ('cost', models.FloatField()),
                ('reported_by', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
