# Generated by Django 5.0.7 on 2024-08-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_housephoto_property'),
        ('regularmaintaince', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenace', to='core.property'),
        ),
    ]
