# Generated by Django 5.0.7 on 2024-08-19 18:45

import django.db.models.deletion
import gasandheat.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSafety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repair_score', models.FloatField()),
                ('report_date', models.DateField()),
                ('due_date', models.DateField()),
                ('expiry_months', models.IntegerField()),
                ('current_eer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('potential_eer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('document', models.FileField(blank=True, null=True, upload_to=gasandheat.models.gas_safety_upload_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='HeatingSafety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repair_score', models.FloatField()),
                ('boiler_condition', models.CharField(max_length=255)),
                ('controller', models.CharField(max_length=255)),
                ('radiators_condition', models.CharField(max_length=255)),
                ('flue_ventilation_condition', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
