# Generated by Django 5.0.7 on 2024-08-19 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('report_date', models.DateField()),
                ('report', models.TextField()),
                ('current_score', models.FloatField()),
                ('potential_score', models.FloatField()),
                ('document', models.FileField(blank=True, null=True, upload_to='epc_reports/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
