# Generated by Django 5.0.7 on 2024-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epcreport',
            name='current_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='epcreport',
            name='potential_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='epcreport',
            name='score',
            field=models.FloatField(),
        ),
    ]
