# Generated by Django 5.0.7 on 2024-08-20 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.TextField()),
                ('score', models.FloatField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('past_inventory', models.BooleanField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory_insception.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inventory_insception.room')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('repair', 'Repair')], max_length=10)),
                ('cleanliness', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/room_conditions/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='inventory_insception.room')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLandlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentlandlord', to='core.agent')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentlandlord', to='core.landlord')),
            ],
            options={
                'unique_together': {('agent', 'landlord')},
            },
        ),
    ]
