# Generated by Django 5.0.7 on 2024-08-25 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.TextField()),
                ('result', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('past_inventory', models.BooleanField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory_insception.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField()),
                ('result', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('created_by', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory_insception.condition')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory_insception.room')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='inventory_insception.room'),
        ),
        migrations.CreateModel(
            name='AgentLandlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentlandlord', to='core.agent')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentlandlord', to='core.landlord')),
            ],
            options={
                'unique_together': {('agent', 'landlord')},
            },
        ),
    ]
