# Generated by Django 5.0.7 on 2024-08-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_insception', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='cleanliness',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
