# Generated by Django 5.0.7 on 2024-08-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_insception', '0002_remove_condition_cleanliness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory_insception.condition')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory_insception.room')),
            ],
        ),
    ]
