# Generated by Django 5.0.7 on 2024-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_insception', '0002_remove_inventory_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
    ]
