# Generated by Django 5.0.7 on 2024-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_insception', '0003_condition_iscomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='description',
            field=models.CharField(default='sample text', max_length=256),
        ),
    ]
