# Generated by Django 5.0.7 on 2024-08-13 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('house_name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('bathroom_count', models.IntegerField()),
                ('living_room_count', models.IntegerField()),
                ('property_type', models.CharField(max_length=50)),
                ('house_age', models.IntegerField()),
                ('floor_map_photos', models.TextField()),
                ('epc_status', models.CharField(max_length=50)),
                ('risk_assessment_percentage', models.FloatField()),
                ('mould_ventilation_percentage', models.FloatField()),
                ('gas_safety', models.BooleanField()),
                ('heat_safety', models.BooleanField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('open_repair_count', models.IntegerField(default=0)),
                ('inspection_count', models.IntegerField(default=0)),
                ('regular_maintenance', models.BooleanField(default=False)),
                ('inventory_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('landlords', models.ManyToManyField(blank=True, related_name='agents', to='core.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='LettingManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('landlord_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_letting_managements', to='core.property')),
                ('tenant_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letting_managements', to='core.property')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='landlords', to='core.property'),
        ),
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.TextField()),
                ('photo_type', models.CharField(max_length=50)),
                ('uploaded_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('maintenance_repair_type', models.CharField(max_length=50)),
                ('performed_by', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='SalesManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('landlord_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('current_tenancy_score', models.FloatField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.landlord')),
                ('properties', models.ManyToManyField(blank=True, related_name='tenants', to='core.property')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='agents', to='core.tenant'),
        ),
    ]
