# Generated by Django 5.0.7 on 2024-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedroom_count',
            field=models.IntegerField(default=0),
        ),
    ]
