# Generated by Django 5.0.7 on 2024-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='unique_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
