# Generated by Django 5.0.7 on 2024-08-21 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landlord_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='HouseItemImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Checkout'), ('inspection', 'Inspection'), ('services', 'Services')], max_length=50)),
                ('upload_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='house_photos/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.housephoto')),
            ],
        ),
    ]
