# Generated by Django 5.0.7 on 2024-08-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_bedroom_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housephoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_photos', to='core.property'),
        ),
    ]
