# Generated by Django 5.0.7 on 2024-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_housephoto_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
