# Generated by Django 5.0.7 on 2024-08-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_housephoto_houseitemimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseitemimages',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_item', to='core.housephoto'),
        ),
    ]
