# Generated by Django 5.0.7 on 2024-08-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_houseitemimages_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlord',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
